-- CAPUBBS archive room schema.
--
-- The archive root is configured outside the database. Store only paths
-- relative to CAPUBBS_ARCHIVE_ROOT in archive_entries.relative_path.
-- entry_key is generated by PHP, not by MySQL:
--   file:   SHA-256(upload timestamp + ':' + SHA-256(file bytes))
--   folder: SHA-256(create timestamp + ':' + random value)
--
-- Timestamps are Unix microseconds. They avoid timezone ambiguity and give
-- file IDs enough entropy when the same content is uploaded more than once.

CREATE TABLE IF NOT EXISTS `archive_entries` (
  `entry_key` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `parent_key` char(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `entry_type` enum('folder','file') COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `relative_path` varchar(1024) COLLATE utf8mb4_unicode_ci NOT NULL,
  `mime_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `byte_size` bigint(20) unsigned NOT NULL DEFAULT '0',
  `content_hash` char(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `created_at` bigint(20) unsigned NOT NULL,
  `updated_at` bigint(20) unsigned NOT NULL,
  `uploader_userid` int(11) unsigned DEFAULT NULL,
  `uploader_username` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `masked_at` bigint(20) unsigned DEFAULT NULL,
  `masked_by_userid` int(11) unsigned DEFAULT NULL,
  `masked_by_username` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `purged_at` bigint(20) unsigned DEFAULT NULL,
  `purged_by` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`entry_key`),
  KEY `archive_parent_listing` (`parent_key`,`masked_at`,`entry_type`,`name`(120)),
  KEY `archive_path_lookup` (`relative_path`(191)),
  KEY `archive_uploader_lookup` (`uploader_userid`,`created_at`),
  KEY `archive_mask_lookup` (`masked_at`,`purged_at`),
  KEY `archive_content_lookup` (`content_hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `archive_downloads` (
  `download_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `entry_key` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `userid` int(11) unsigned NOT NULL,
  `username` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  `downloaded_at` bigint(20) unsigned NOT NULL,
  `ip` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `user_agent` varchar(512) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `byte_size` bigint(20) unsigned NOT NULL DEFAULT '0',
  `status` enum('started','completed') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'started',
  PRIMARY KEY (`download_id`),
  KEY `archive_download_entry_time` (`entry_key`,`downloaded_at`),
  KEY `archive_download_user_time` (`userid`,`downloaded_at`),
  KEY `archive_download_time` (`downloaded_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
